FROM andrius/asterisk:latest

# テンプレートとスクリプトをコピー
COPY asterisk/pjsip.conf.template /etc/asterisk/pjsip.conf.template
COPY asterisk/manager.conf.template /etc/asterisk/manager.conf.template
COPY asterisk/extensions.conf /etc/asterisk/extensions.conf
COPY asterisk/rtp.conf /etc/asterisk/rtp.conf
COPY asterisk/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh
RUN chown -R asterisk:asterisk /etc/asterisk

ENTRYPOINT ["/entrypoint.sh"]
